server.port=8082
spring.config.import=optional:classpath:application-local.properties

spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

qgchat.auth.token-ttl-hours=12
qgchat.auth.password-reset-ttl-minutes=15
